### ISSUE TITLE
issue with ranger-presto-plugin

### ISSUE THREAD

**Issue by yogesh1811** [varunrao/aws-blog-emr-ranger#7]
ranger-hive-plugin working as expected but ranger-presto-plugin is not working.
when go to presto tab in hue getting below error.

`An error occurred while calling o48.execute. : java.sql.SQLException: Query failed (#20200616_134351_00099_qumku): Access Denied: Cannot select from columns [user_cookie, ad_id, impression_id, hour, request_begin_time, page, ip_address, clicked, day, user_agent] in table or view tblanalyst1 at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1840) at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1750) at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:119) at`

although from EMR master node cli
$presto-cli --catalog hive --schema default --user analyst1

presto:default> SELECT * FROM tblanalyst1;
Query 20200616_134905_00106_qumku failed: Access Denied: Cannot select from columns [user_cookie, ad_id, impression_id, hour, request_begin_time, page, ip_address, clicked, day, user_agent] in table or view tblanalyst1

**Comment by varunrao** [comment]
Which version are you using? V1 or V2? The error is consistent which
indicates a policy sync issue.
Can you check the error if you add thenpolicu under presto on Ranger Admin?

**Comment by yogesh1811** [comment]
I am using V1 version. 

today I am trying to install plugin myself thought not to use from EMR-step but manually running "v1/scripts/emr-steps/install-presto-ranger-plugin.sh"
Plugin got installed and after that installed policy getting

`Access Denied: Cannot access catalog hive at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1840) at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1750`

after this again updated presto-policy from ranger admin ui but still get same error.

When I trying to reinstall from master node and curl to ranger-server as follow 

`curl -iv -u admin:admin -d @ranger-presto-repo.json -H "Content-Type: application/json" -X POST http://$ranger_server_fqdn:6080/service/public/v2/api/service/
curl -iv -u admin:admin -d @ranger-presto-policy-general.json -H "Content-Type: application/json" -X POST http://$ranger_server_fqdn:6080/service/public/v2/api/policy/apply
curl -iv -u admin:admin -d @ranger-presto-policy-information-schema.json -H "Content-Type: application/json" -X POST http://$ranger_server_fqdn:6080/service/public/v2/api/policy/apply
curl -iv -u admin:admin -d @ranger-presto-policy-analyst1.json -H "Content-Type: application/json" -X POST http://$ranger_server_fqdn:6080/service/public/v2/api/policy/apply
curl -iv -u admin:admin -d @ranger-presto-policy-analyst2.json -H "Content-Type: application/json" -X POST http://$ranger_server_fqdn:6080/service/public/v2/api/policy/apply`

I found error while adding them on ranger-admin log file

`2020-06-17 16:07:51,722 [http-bio-6080-exec-8] **ERROR** apache.ranger.authorization.hadoop.config.RangerConfiguration (RangerConfiguration.java:60) - addResourceIfReadable(**ranger-presto-audit**.xml): couldn't find resource file location
2020-06-17 16:07:51,723 [http-bio-6080-exec-8] ERROR apache.ranger.authorization.hadoop.config.RangerConfiguration (RangerConfiguration.java:60) - addResourceIfReadable(**ranger-presto-securit**y.xml): couldn't find resource file location
2020-06-17 16:07:51,724 [http-bio-6080-exec-8] ERROR apache.ranger.authorization.hadoop.config.RangerConfiguration (RangerConfiguration.java:60) - addResourceIfReadable(**ranger-presto-policymgr-ssl**.xml): couldn't find resource file location`

**Comment by varunrao** [comment]
Can you confirm the Ranger Version? You much be on Ranger 2.0 to have Presto support.

**Comment by yogesh1811** [comment]
its ranger-2.1.0

**Comment by varunrao** [comment]
Ok. Did you replace the " ranger_server_fqdn " in the curl command with the
ranger ip?
Do you see the prestodev service on the Ranger UI.?

**Comment by yogesh1811** [comment]
yes after posting curl i have seen prestodev created on ranger-admin. verified from ranger UI
today I have removed everything and trying to setup from starting.  if i follow AWS CF template i get this error.
if possible can you give me steps to follow.

**Comment by yogesh1811** [comment]
with fresh setup of ranger-admin version ranger-2.1.0-SNAPSHOT-admin
and emr cluster with V1 getting below error for querying from hue

`An error occurred while calling o66.execute. : java.sql.SQLException: Query failed (#20200618_163239_00011_e2zxf): Access Denied: Cannot select from columns [user_cookie, ad_id, impression_id, hour, request_begin_time, page, ip_address, clicked, day, user_agent] in table or view tblanalyst1`

though i can see them in left panel in hue.

after that i tried to update prestodev policy from ranger ui
add all these specific columns in Analyst1Policy but still same issue.

But for hive plugin working as expected analyst1 does not have select on tblanalyst2 and when add permission from ranger-ui it got accessible as expected worked like charm.

Presto is causing some issue.

while I found Ranger-admin log some error as ...
`2020-06-18 16:31:09,705 [timed-executor-pool-0] ERROR apache.ranger.services.presto.client.PrestoConnectionManager (PrestoConnectionManager.java:57) - Error connecting to Presto repository: prestodev using config: {enable.hive.metastore.lookup=false, jdbc.driverClassName=io.prestosql.jdbc.PrestoDriver, hive.site.file.path=, jdbc.url=jdbc:presto://XXXXXXX:8889/hive/default, username=prestodev}
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at org.apache.ranger.services.presto.client.PrestoClient.initConnection(PrestoClient.java:83)
	at org.apache.ranger.services.presto.client.PrestoClient.access$000(PrestoClient.java:45)
	at org.apache.ranger.services.presto.client.PrestoClient$1.run(PrestoClient.java:70)
	at org.apache.ranger.services.presto.client.PrestoClient$1.run(PrestoClient.java:68)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.ranger.services.presto.client.PrestoClient.init(PrestoClient.java:68)
	at org.apache.ranger.services.presto.client.PrestoClient.<init>(PrestoClient.java:64)
	at org.apache.ranger.services.presto.client.PrestoConnectionManager$1.call(PrestoConnectionManager.java:51)
	at org.apache.ranger.services.presto.client.PrestoConnectionManager$1.call(PrestoConnectionManager.java:48)
	at org.apache.ranger.plugin.util.TimedEventUtil.timedTask(TimedEventUtil.java:40)
	at org.apache.ranger.services.presto.client.PrestoConnectionManager.getPrestoConnection(PrestoConnectionManager.java:55)`

if this gives any clue

**Comment by varunrao** [comment]
Found the issue. The default script was not using the prestoDB version of the installer. It was using prestoSQL. It should be fixed with the latest commit.

**Comment by varunrao** [comment]
@yogesh1811  - can you please update the issue once you have verified the fix? thx.

**Comment by yogesh1811** [comment]
its showing db and I am able to select via Hue(Presto) but when I have updated policy in Ranger admin ui (prestodev) repo. changes are not reflecting. even after re-login in hue.
What is sync time with default i did not change anything.
One more thing do I need to move to EMR version "emr-5.30.0" as  see changes in install-presto-ranger-plugin.sh?

**Comment by varunrao** [comment]
You should use the hivedev policy as you are using the default hive
catalog. Prestodev will be for other presto connectors.

**Comment by yogesh1811** [comment]
okay "hivedev" its working as expected but in which case we need "Prestodev" repo.

I have tested with other client (Datagrip) connect presto cluster over JDBC (jdbc:presto://masternodeip:8889/hive) with passing user name only. it working with "hivedev" repo only. 

other than that i test with presto-cli (master-node) as
presto-cli --catalog hive --schema default --user analyst1
this is also working, 

Both case it just need user name but how to make password mandatory ?

**Comment by varunrao** [comment]
That would require you to enable LDAP with Presto.

**Comment by varunrao** [comment]
Closing this as the latest fix solved the Presto issue
